name: CI

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    if: github.ref == 'refs/heads/github-ciXXX'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test

  build:
    if: github.ref == 'refs/heads/github-ciXXX'
    runs-on: ubuntu-latest
    #needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        uses: docker/build-push-action@v1
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ github.repository }}
          tag_with_ref: true
          tag_with_sha: true
          tags: github-ci
          build_args: version=${{ github.sha }}

  deploy:
    if: github.ref == 'refs/heads/github-ci'
    runs-on: ubuntu-latest
    #needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy
        uses: chipsu/rancher-deploy-action@v1
        with:
          url: ${{ secrets.RANCHER_URL }}
          access_key: ${{ secrets.RANCHER_ACCESS_KEY }}
          secret_key: ${{ secrets.RANCHER_SECRET_KEY }}
          stack: test-stack-123
        env:
          WEB_IMAGE: ${{ secrets.DOCKER_REGISTRY }}/${{ github.repository }}:sha-0963da4
          MEDIA_SOURCE: ${{ secrets.MEDIA_SOURCE }}
